version: '2'
services:
    reviewmanager4-app:
        image: reviewmanager4
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://reviewmanager4-postgresql:5432/reviewmanager4
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    reviewmanager4-postgresql:
        extends:
            file: postgresql.yml
            service: reviewmanager4-postgresql
