version: '2'
services:
    reviewmanager4-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/reviewmanager4/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=reviewmanager4
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
